version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todayus-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://today-us.cnkosmsw0ixi.ap-northeast-2.rds.amazonaws.com:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=erdwvudr2qvud1!
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=always
    restart: unless-stopped
