version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todayus-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=always
    restart: unless-stopped
