services:
  postgres:
    image: postgres:latest
    container_name: todayus-postgres
    environment:
      POSTGRES_DB: todayus
      POSTGRES_USER: todayus
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: