[variables]
NIXPACKS_JAVA_VERSION = "17"

[phases.build]
cmd = "cd backend && chmod +x gradlew && ./gradlew clean build -x test"

[phases.start]
cmd = "cd backend && java -jar build/libs/*.jar"

[start]
cmd = "cd backend && java -jar build/libs/*.jar"