[phases.setup]
nixPkgs = ['openjdk17']

[phases.build]
cmds = ['chmod +x ./gradlew', './gradlew clean build -x test --no-daemon']

[start]
cmd = 'java $JAVA_OPTS -jar build/libs/todayus-backend.jar'

[variables]
JAVA_OPTS = '-Xmx512m -Xms256m'