[build]
builder = "nixpacks"
buildCommand = "cd backend && ./gradlew clean build"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "cd backend && java -jar build/libs/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Nixpacks 설정
[variables]
NIXPACKS_JAVA_VERSION = "17"
NIXPACKS_BUILD_CMD = "cd backend && ./gradlew clean build"