[build]
builder = "nixpacks"
buildCommand = "./gradlew clean build -x test"
watchPatterns = ["**"]

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# 환경 변수 설정 (production에서 override 필요)
[variables]
JAVA_OPTS = "-Xmx512m -Xms256m"
SPRING_PROFILES_ACTIVE = "production"
SERVER_PORT = "8080"