spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/todayus}
    username: ${SPRING_DATASOURCE_USERNAME:todayus}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "${BASE_URL:https://todayus-production.up.railway.app}/login/oauth2/code/{registrationId}"

          kakao:
            client-id: ${KAKAO_CLIENT_ID:your-kakao-client-id}
            client-secret: ${KAKAO_CLIENT_SECRET:your-kakao-client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "${BASE_URL:https://todayus-production.up.railway.app}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: ${PORT:8080}
  forward-headers-strategy: native

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET:myVerySecretKeyForJWTTokenGeneration123456789}
  token-validity-in-seconds: 86400

openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key}

logging:
  level:
    com.todayus: INFO
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN
    org.springframework.web.client: WARN
    org.springframework.security.oauth2.client: WARN
    ROOT: INFO

app:
  oauth2:
    authorized-redirect-uris:
      - ${BASE_URL:https://todayus-production.up.railway.app}
      - ${FRONTEND_URL:http://localhost:53153}
