// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg_QGjsFWbFQSLTQo1YMDDENdBxjbGNSo',
    appId: '1:873410590555:web:be4ab45429e16b9e8ecc7e',
    messagingSenderId: '873410590555',
    projectId: 'todayus-c00d2',
    authDomain: 'todayus-c00d2.firebaseapp.com',
    storageBucket: 'todayus-c00d2.firebasestorage.app',
    measurementId: 'G-8SFRFP6NXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_QGjsFWbFQSLTQo1YMDDENdBxjbGNSo',
    appId: '1:873410590555:android:be4ab45429e16b9e8ecc7e', // Android용 앱 ID (추후 등록 시 업데이트)
    messagingSenderId: '873410590555',
    projectId: 'todayus-c00d2',
    storageBucket: 'todayus-c00d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg_QGjsFWbFQSLTQo1YMDDENdBxjbGNSo',
    appId: '1:873410590555:ios:be4ab45429e16b9e8ecc7e', // iOS용 앱 ID (추후 등록 시 업데이트)
    messagingSenderId: '873410590555',
    projectId: 'todayus-c00d2',
    storageBucket: 'todayus-c00d2.firebasestorage.app',
    iosBundleId: 'com.todayus.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg_QGjsFWbFQSLTQo1YMDDENdBxjbGNSo',
    appId: '1:873410590555:ios:be4ab45429e16b9e8ecc7e', // macOS는 iOS와 동일한 설정 사용
    messagingSenderId: '873410590555',
    projectId: 'todayus-c00d2',
    storageBucket: 'todayus-c00d2.firebasestorage.app',
    iosBundleId: 'com.todayus.app',
  );
}